// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using LF.Table;

namespace LF
{
    public sealed class DuoyuyanDataRow : DuoyuyanBaseDataRow
    {
        public DuoyuyanDataRow(DRduoyuyan datarow, int index) : base(datarow, index)
        {

        }
    }
}