// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using LF.Table;

namespace LF
{
    public sealed class HeroesDataRow : HeroesBaseDataRow
    {
        public HeroesDataRow(DRheroes datarow, int index) : base(datarow, index)
        {

        }
    }
}