// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using Chanto.Table;

namespace Chanto.Table
{
    public sealed class Heroes_levelupDataRow : Heroes_levelupBaseDataRow
    {
        public Heroes_levelupDataRow(DRheroes_levelup datarow, int index) : base(datarow, index)
        {

        }
    }
}