// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using Chanto.Table;

namespace Chanto.Table
{
    public sealed class Heroes_campDataRow : Heroes_campBaseDataRow
    {
        public Heroes_campDataRow(DRheroes_camp datarow, int index) : base(datarow, index)
        {

        }
    }
}