// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using LF.Table;

namespace LF
{
    public sealed class MailDataRow : MailBaseDataRow
    {
        public MailDataRow(DRmail datarow, int index) : base(datarow, index)
        {

        }
    }
}