// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using LF.Table;

namespace LF
{
    public sealed class MovieDataRow : MovieBaseDataRow
    {
        public MovieDataRow(DRmovie datarow, int index) : base(datarow, index)
        {

        }
    }
}