// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using LF.Table;

namespace LF
{
    public sealed class PveDataRow : PveBaseDataRow
    {
        public PveDataRow(DRpve datarow, int index) : base(datarow, index)
        {

        }
    }
}