// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using Chanto.Table;

namespace Chanto.Table
{
    public sealed class ScienceDataRow : ScienceBaseDataRow
    {
        public ScienceDataRow(DRscience datarow, int index) : base(datarow, index)
        {

        }
    }
}