// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using Chanto.Table;

namespace Chanto.Table
{
    public sealed class ScoreDataRow : ScoreBaseDataRow
    {
        public ScoreDataRow(DRscore datarow, int index) : base(datarow, index)
        {

        }
    }
}