// <auto-generated>
//  You can expand your configuration logic here.
// </auto-generated>
using LF.Table;

namespace LF
{
    public sealed class SkillDataRow : SkillBaseDataRow
    {
        public SkillDataRow(DRskill datarow, int index) : base(datarow, index)
        {

        }
    }
}