// <auto-generated>
//  automatically generated by table tool, do not modify
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Chanto.Table
{
	public class ConfigManager : Singleton<ConfigManager>
    {
        private Dictionary<string, byte[]> dataTableAssets = new Dictionary<string, byte[]>(100);
        public Dictionary<string, byte[]> DataTableAssets { get { return dataTableAssets; } }

        /// <summary>
        /// 判断表名是否合法
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <returns>true-合法, false-不合法</returns>
        public bool IsValidTable(string tableName)
        {
            bool isValid = false;

            switch (tableName)
            {
                case "activityCenter": { isValid = true; break; }
                case "adapter": { isValid = true; break; }
                case "const": { isValid = true; break; }
                case "debug_cmd": { isValid = true; break; }
                case "device": { isValid = true; break; }
                case "effect": { isValid = true; break; }
                case "heroes_uipos": { isValid = true; break; }
                case "mainTopRightIcons": { isValid = true; break; }
                case "prefab": { isValid = true; break; }
                case "ui": { isValid = true; break; }
                case "atlas": { isValid = true; break; }
                case "sprites": { isValid = true; break; }

                default:
                    break;
            }

            return isValid;
        }
    }
}