// <auto-generated>
//  automatically generated by table tool, do not modify
// </auto-generated>
using System;
using System.Collections.Generic;
using UnityEngine;

namespace LF
{
	public class TableManager : Singleton<TableManager>
    {
        private Dictionary<string, byte[]> dataTableAssets = new Dictionary<string, byte[]>(100);
        public Dictionary<string, byte[]> DataTableAssets { get { return dataTableAssets; } }

        private Dictionary<string, BaseTable> dataTables = new Dictionary<string, BaseTable>(100);

        private Dictionary<Type, string> nameCache = new Dictionary<Type, string>(200);

        private bool[] default_bool = new bool[0];
        private short[] default_short = new short[0];
        private int[] default_int = new int[0];
        private float[] default_float = new float[0];
        private string[] default_string = new string[0];

        #region Data Method

        public bool GetBool(string tableName, string id, string column, bool defaultValue = false)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetBoolValue(id, column, defaultValue);
        }

        public bool[] GetBoolArray(string tableName, string id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return default_bool;

            var result = dataTable.GetBoolArray(id, column);
            if (null == result)
                return default_bool;

            return result;
        }
        
        public short GetShort(string tableName, string id, string column, short defaultValue = 0)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetShortValue(id, column, defaultValue);
        }

        public short[] GetShortArray(string tableName, string id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return default_short;

            var result = dataTable.GetShortArray(id, column);
            if (null == result)
                return default_short;

            return result;
        }
        
        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public int GetInt(string tableName, string id, string column, int defaultValue = 0)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetIntValue(id, column, defaultValue);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public int[] GetIntArray(string tableName, string id, string column) 
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return default_int;

            var result = dataTable.GetIntArray(id, column);
            if (null == result)
                return default_int;

            return result;
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public float GetFloat(string tableName, string id, string column, float defaultValue = 0.0f) 
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetFloatValue(id, column, defaultValue);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public float[] GetFloatArray(string tableName, string id, string column) 
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return default_float;

            var result = dataTable.GetFloatArray(id, column);
            if (null == result)
                return default_float;

            return result;
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public string GetString(string tableName, string id, string column, string defaultValue = "") 
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetStringValue(id, column, defaultValue);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public int GetStringArrayLength(string tableName, string id, string column) 
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return 0;

            return dataTable.GetStringArrayLength(id, column);
        }
        
        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public string[] GetStringArray(string tableName, string id, string column) 
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return default_string;

            var result = dataTable.GetStringArray(id, column);
            if (null == result)
                return default_string;

            return result;
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public string GetStringArrayItem(string tableName, string id, string column, int index, string defaultValue = "") 
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetStringArrayItem(id, column, index, defaultValue);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public int GetInt(string tableName, int id, string column, int defaultValue = 0)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetIntValue(id, column, defaultValue);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public int[] GetIntArray(string tableName, int id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return default_int;

            var result = dataTable.GetIntArray(id, column);
            if (null == result)
                return default_int;

            return result;
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public float GetFloat(string tableName, int id, string column, float defaultValue = 0.0f)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetFloatValue(id, column, defaultValue);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public float[] GetFloatArray(string tableName, int id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return default_float;

            var result = dataTable.GetFloatArray(id, column);
            if (null == result)
                return default_float;

            return result;
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public string GetString(string tableName, int id, string column, string defaultValue = "")
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetStringValue(id, column, defaultValue);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public int GetStringArrayLength(string tableName, int id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return 0;

            return dataTable.GetStringArrayLength(id, column);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public string[] GetStringArray(string tableName, int id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return default_string;

            var result = dataTable.GetStringArray(id, column);
            if (null == result)
                return default_string;

            return result;
        }
        
        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public string GetStringArrayItem(string tableName, int id, string column, int index, string defaultValue = "")
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return defaultValue;

            return dataTable.GetStringArrayItem(id, column, index, defaultValue);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public Dictionary<int, int> GetDictionaryII(string tableName, int id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return null;

            return dataTable.GetDictionaryII(id, column);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public Dictionary<int, string> GetDictionaryIS(string tableName, int id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return null;

            return dataTable.GetDictionaryIS(id, column);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public Dictionary<string, int> GetDictionarySI(string tableName, int id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return null;

            return dataTable.GetDictionarySI(id, column);
        }

        //[Obsolete("This function is not recommended, you can call GetDataRow<T>")]
        public Dictionary<string, string> GetDictionarySS(string tableName, int id, string column)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return null;

            return dataTable.GetDictionarySS(id, column);
        }
        
        #endregion Data Method
        
        #region Table Method

        /// <summary>
        /// 获得表
        /// </summary>
        /// <typeparam name="T">继承自BaseTable的表类型</typeparam>
        /// <returns>表对象</returns>
        public T GetTable<T>() where T : BaseTable, new()
        {
            Type type = typeof(T);
            
            string tableName;
            if (!nameCache.TryGetValue(type, out tableName))
            {
                string typeName = type.Name;
                int index = typeName.LastIndexOf("Table");
                if (index <= 0)
                {
                    Debug.LogErrorFormat("The T must inherit from BaseTable");
                    return null;
                }

                tableName = typeName.Substring(0, index);

                if (!this.IsValidTable(tableName))
                    tableName = this.LowerFirstChar(tableName);

                if (!this.IsValidTable(tableName))
                {
                    Debug.LogErrorFormat("Can not find {0}, please check.", typeName);
                    return null;
                }

                if (!nameCache.ContainsKey(type))
                    nameCache.Add(type, tableName);
            }

            if (!this.dataTables.ContainsKey(tableName))
                this.dataTables.Add(tableName, new T());

            return (T)this.dataTables[tableName];
        }
        
        /// <summary>
        /// 按行遍历表格
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="callback"></param>
        public void dumpTable(string tableName, System.Func<BaseDataRow, bool> callback)
        {
            var table = this.GetTable(tableName);
            if (null == table)
                return;

            table.VisitTable(callback);
        }

        /// <summary>
        /// Lua侧获得所有表数据
        /// </summary>
        /// <param name="tableName"></param>
        /// <returns></returns>
        public CSLuaTable[] GetAllDataRows(string tableName)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return null;

            return dataTable.GetAllLuaData();
        }
        
        /// <summary>
        /// 获得表数据的条数
        /// </summary>
        /// <param name="tableName">数据表名</param>
        /// <returns></returns>
        public int GetDataCount(string tableName)
        {
            BaseTable dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return 0;

            return dataTable.GetDataCount();
        }
        
        #endregion Table Method

        #region DataRow Method

        /// <summary>
        /// 判断表的数据行是否存在
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="id"></param>
        /// <returns></returns>
        public bool HasDataRow<T>(int id) where T : BaseDataRow
        {
            Type type = typeof(T);
            
            string tableName;
            if(!nameCache.TryGetValue(type, out tableName))
            {
                string typeName = type.Name;
                int index = typeName.LastIndexOf("DataRow");
                if (index <= 0)
                {
                    Debug.LogError("The T must inherit from BaseDataRow");
                    return false;
                }

                tableName = typeName.Substring(0, index);

                if (!this.IsValidTable(tableName))
                    tableName = this.LowerFirstChar(tableName);

                if (!this.IsValidTable(tableName))
                {
                    Debug.LogErrorFormat("Can not find {0}, please check.", typeName);
                    return false;
                }
                
                if(!nameCache.ContainsKey(type))
                    nameCache.Add(type, tableName);
            }

            BaseTable table = this.GetTable(tableName);
            if (null != table)
                return table.HasDataRow(id);

            return false;
        }

        /// <summary>
        /// 判断表的数据行是否存在
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="id"></param>
        /// <returns></returns>
        public bool HasDataRow<T>(string id) where T : BaseDataRow
        {
            Type type = typeof(T);
            
            string tableName;
            if(!nameCache.TryGetValue(type, out tableName))
            {
                string typeName = type.Name;

                int index = typeName.LastIndexOf("DataRow");
                if (index <= 0)
                {
                    Debug.LogErrorFormat("The T must inherit from BaseDataRow");
                    return false;
                }

                tableName = typeName.Substring(0, index);

                if (!this.IsValidTable(tableName))
                    tableName = this.LowerFirstChar(tableName);

                if (!this.IsValidTable(tableName))
                {
                    Debug.LogErrorFormat("Can not find {0}, please check.", typeName);
                    return false;
                }
                
                if(!nameCache.ContainsKey(type))
                    nameCache.Add(type, tableName);
            }
            
            BaseTable table = this.GetTable(tableName);
            if (null != table)
                return table.HasDataRow(id);

            return false;
        }
        
        /// <summary>
        /// 获得表的数据行
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="id"></param>
        /// <returns></returns>
        public T GetDataRow<T>(int id) where T : BaseDataRow
        {
            Type type = typeof(T);
            
            string tableName;
            if(!nameCache.TryGetValue(type, out tableName))
            {
                string typeName = type.Name;
                int index = typeName.LastIndexOf("DataRow");
                if (index <= 0)
                {
                    Debug.LogErrorFormat("The T must inherit from BaseDataRow");
                    return null;
                }

                tableName = typeName.Substring(0, index);

                if (!this.IsValidTable(tableName))
                    tableName = this.LowerFirstChar(tableName);

                if (!this.IsValidTable(tableName))
                {
                    Debug.LogErrorFormat("Can not find {0}, please check.", typeName);
                    return null;
                }
                
                if(!nameCache.ContainsKey(type))
                    nameCache.Add(type, tableName);
            }
            
            BaseTable table = this.GetTable(tableName);
            if (null != table)
                return (T)table.GetTableRow(id);

            return null;
        }

        /// <summary>
        /// 获得表的数据行
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="id"></param>
        /// <returns></returns>
        public T GetDataRow<T>(string id) where T : BaseDataRow
        {
            Type type = typeof(T);
            
            string tableName;
            if(!nameCache.TryGetValue(type, out tableName))
            {
                string typeName = typeof(T).Name;
                int index = typeName.LastIndexOf("DataRow");
                if (index <= 0)
                {
                    Debug.LogErrorFormat("The T must inherit from BaseDataRow");
                    return null;
                }

                tableName = typeName.Substring(0, index);

                if (!this.IsValidTable(tableName))
                    tableName = this.LowerFirstChar(tableName);

                if (!this.IsValidTable(tableName))
                {
                    Debug.LogErrorFormat("Can not find {0}, please check.", typeName);
                    return null;
                }
                
                if(!nameCache.ContainsKey(type))
                    nameCache.Add(type, tableName);
            }
            
            BaseTable table = this.GetTable(tableName);
            if (null != table)
                return (T)table.GetTableRow(id);

            return null;
        }

        /// <summary>
        /// 根据行号获得表的数据行
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="index">行号,从0开始</param>
        /// <returns></returns>
        public T GetDataRowByIndex<T>(int index) where T : BaseDataRow
        {
            Type type = typeof(T);

            string tableName;
            if (!nameCache.TryGetValue(type, out tableName))
            {
                string typeName = typeof(T).Name;
                int tmpIndex = typeName.LastIndexOf("DataRow");
                if (tmpIndex <= 0)
                {
                    Debug.LogErrorFormat("The T must inherit from BaseDataRow");
                    return null;
                }

                tableName = typeName.Substring(0, tmpIndex);

                if (!this.IsValidTable(tableName))
                    tableName = this.LowerFirstChar(tableName);

                if (!this.IsValidTable(tableName))
                {
                    Debug.LogErrorFormat("Can not find {0}, please check.", typeName);
                    return null;
                }

                if (!nameCache.ContainsKey(type))
                    nameCache.Add(type, tableName);
            }

            BaseTable table = this.GetTable(tableName);
            if (null != table)
                return (T)table.GetTableRowByIndex(index);

            return null;
        }
        
        /// <summary>
        /// Lua侧获得行数据(为了兼容Lua老接口而设计,会使行数据产生两份内存,不建议使用)
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <param name="id">行ID</param>
        /// <returns></returns>
        public CSLuaTable GetDataRow(string tableName, int id)
        {
            var dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return null;

            var dataRow = dataTable.GetTableRow(id);
            if (null == dataRow)
                return null;

            return dataRow.GetLuaTable();
        }

        /// <summary>
        /// Lua侧获得行数据(为了兼容Lua老接口而设计,会使行数据产生两份内存,不建议使用)
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <param name="id">行ID</param>
        /// <returns></returns>
        public CSLuaTable GetDataRow(string tableName, string id)
        {
            var dataTable = this.GetTable(tableName);
            if (null == dataTable)
                return null;

            var dataRow = dataTable.GetTableRow(id);
            if (null == dataRow)
                return null;

            return dataRow.GetLuaTable();
        }

        /// <summary>
        /// 根据Id获得数据行(Lua侧获取行数据建议使用此接口)
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="id"></param>
        public BaseDataRow GetDataRowById(string tableName, int id)
        {
            var table = this.GetTable(tableName);
            if (null == table)
                return null;

            return table.GetTableRow(id);
        }

        /// <summary>
        /// 根据Id获得数据行(Lua侧获取行数据建议使用此接口)
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="id"></param>
        public BaseDataRow GetDataRowById(string tableName, string id)
        {
            var table = this.GetTable(tableName);
            if (null == table)
                return null;

            return table.GetTableRow(id);
        }

        /// <summary>
        /// 根据行号获得数据行(Lua侧获取行数据建议使用此接口)
        /// </summary>
        /// <param name="tableName"></param>
        /// <param name="index"></param>
        public BaseDataRow GetDataRowByIndex(string tableName, int index)
        {
            var table = this.GetTable(tableName);
            if (null == table)
                return null;

            return table.GetTableRowByIndex(index);
        }

        #endregion DataRow Method

        #region Framework Method
        
        /// <summary>
        /// 重置所有表
        /// </summary>
        public void ResetAllTable()
        {
            foreach(var table in this.dataTables)
            {
                if (null != table.Value)
                    table.Value.ResetTable();
            }
        }
        
        /// <summary>
        /// 根据表名获得表对象
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <returns>表对象</returns>
        private BaseTable GetTable(string tableName)
        {
            BaseTable table = null;
            if (this.dataTables.TryGetValue(tableName, out table) && null != table)
                return table;
            
            if (!this.IsValidTable(tableName))
            {
                Debug.LogErrorFormat("Can not find the table {0}", tableName);
                return null;
            }
            
            if (!this.dataTables.ContainsKey(tableName))
            {
                string tableType = string.Format("LF.{0}Table", this.UpperFirstChar(tableName));
                table = (BaseTable)Activator.CreateInstance(Type.GetType(tableType));

                this.dataTables.Add(tableName, table);
            }
            
            return this.dataTables[tableName];
        }

        /// <summary>
        /// 将字符串的首字母大写
        /// </summary>
        /// <param name="input">输入字符串</param>
        /// <returns></returns>
        private string UpperFirstChar(string input)
        {
            if (string.IsNullOrEmpty(input))
                return string.Empty;

            if (input.Length <= 1)
                return input.ToUpperInvariant();
            else
                return input.Substring(0, 1).ToUpperInvariant() + input.Substring(1);
        }

        /// <summary>
        /// 将字符串的首字母大写
        /// </summary>
        /// <param name="input">输入字符串</param>
        /// <returns></returns>
        private string LowerFirstChar(string input)
        {
            if (string.IsNullOrEmpty(input))
                return string.Empty;

            if (input.Length <= 1)
                return input.ToUpperInvariant();
            else
                return input.Substring(0, 1).ToLowerInvariant() + input.Substring(1);
        }

        /// <summary>
        /// 判断表名是否合法
        /// </summary>
        /// <param name="tableName">表名</param>
        /// <returns>true-合法, false-不合法</returns>
        public bool IsValidTable(string tableName)
        {
            bool isValid = false;

            switch (tableName)
            {
                case "achievement_main_page": { isValid = true; break; }
                case "achievement_stage_reward": { isValid = true; break; }
                case "achievement": { isValid = true; break; }
                case "ActHeroicRise": { isValid = true; break; }
                case "activity_compose_show": { isValid = true; break; }
                case "activity_compose": { isValid = true; break; }
                case "activity_exchange_festival": { isValid = true; break; }
                case "activity_exchange": { isValid = true; break; }
                case "activity_hero_combination": { isValid = true; break; }
                case "activity_hero": { isValid = true; break; }
                case "activity_heroquest": { isValid = true; break; }
                case "activity_market": { isValid = true; break; }
                case "activity_memory": { isValid = true; break; }
                case "activity_panel": { isValid = true; break; }
                case "ActivityEntranceData": { isValid = true; break; }
                case "ad_mov": { isValid = true; break; }
                case "AD1_movie": { isValid = true; break; }
                case "affect_num": { isValid = true; break; }
                case "affect_way": { isValid = true; break; }
                case "alliance_authority": { isValid = true; break; }
                case "alliance_battle_order": { isValid = true; break; }
                case "alliance_building": { isValid = true; break; }
                case "alliance_buildingdisplay": { isValid = true; break; }
                case "alliance_calendar": { isValid = true; break; }
                case "alliance_chatgift": { isValid = true; break; }
                case "alliance_dkp": { isValid = true; break; }
                case "alliance_gift_group": { isValid = true; break; }
                case "alliance_heroes": { isValid = true; break; }
                case "alliance_item": { isValid = true; break; }
                case "alliance_league": { isValid = true; break; }
                case "alliance_position": { isValid = true; break; }
                case "alliance_prize_quiz": { isValid = true; break; }
                case "alliance_quiz_char": { isValid = true; break; }
                case "alliance_skill": { isValid = true; break; }
                case "alliancedailyquest": { isValid = true; break; }
                case "alliancedonate": { isValid = true; break; }
                case "alliancelevel": { isValid = true; break; }
                case "anniv_main": { isValid = true; break; }
                case "appearance_entrance": { isValid = true; break; }
                case "appearance": { isValid = true; break; }
                case "arena_team_stage": { isValid = true; break; }
                case "arms": { isValid = true; break; }
                case "army_strength_lv": { isValid = true; break; }
                case "battle_animation": { isValid = true; break; }
                case "battle_position": { isValid = true; break; }
                case "battlepass_quest": { isValid = true; break; }
                case "battlepass": { isValid = true; break; }
                case "buff_display": { isValid = true; break; }
                case "building_effect_way": { isValid = true; break; }
                case "building": { isValid = true; break; }
                case "buildingState": { isValid = true; break; }
                case "camp_effect": { isValid = true; break; }
                case "car_repair_spend": { isValid = true; break; }
                case "chapter_1": { isValid = true; break; }
                case "chat_assistant": { isValid = true; break; }
                case "circular_relic": { isValid = true; break; }
                case "city_battle_quest": { isValid = true; break; }
                case "city_battle": { isValid = true; break; }
                case "communitys": { isValid = true; break; }
                case "country_flag": { isValid = true; break; }
                case "countryflag": { isValid = true; break; }
                case "coupon": { isValid = true; break; }
                case "cross_server_alliance_cost": { isValid = true; break; }
                case "cross_server_cost": { isValid = true; break; }
                case "crypticsignal": { isValid = true; break; }
                case "DayAct": { isValid = true; break; }
                case "deer_capture": { isValid = true; break; }
                case "developquest_member_refresh_cost": { isValid = true; break; }
                case "developquest_member": { isValid = true; break; }
                case "developquest": { isValid = true; break; }
                case "developrefresh": { isValid = true; break; }
                case "device_adapter": { isValid = true; break; }
                case "dog_intimacy": { isValid = true; break; }
                case "doomsday_challenge_quest": { isValid = true; break; }
                case "doomsday_challenge": { isValid = true; break; }
                case "duoyuyan": { isValid = true; break; }
                case "equip_book": { isValid = true; break; }
                case "equip_clean_up_item": { isValid = true; break; }
                case "equip_effect_priority": { isValid = true; break; }
                case "equip_make_menu": { isValid = true; break; }
                case "equip_make": { isValid = true; break; }
                case "equip_material": { isValid = true; break; }
                case "equip_random_effect": { isValid = true; break; }
                case "equip_strengthen": { isValid = true; break; }
                case "equip_suit_effect": { isValid = true; break; }
                case "equipment": { isValid = true; break; }
                case "event_dailyunlock": { isValid = true; break; }
                case "event": { isValid = true; break; }
                case "expedition_buff": { isValid = true; break; }
                case "expedition_building": { isValid = true; break; }
                case "expedition_effect": { isValid = true; break; }
                case "expedition_group": { isValid = true; break; }
                case "festival_icon": { isValid = true; break; }
                case "field_monster": { isValid = true; break; }
                case "fight_camp": { isValid = true; break; }
                case "fight_infinite": { isValid = true; break; }
                case "first_occupation": { isValid = true; break; }
                case "fishery_harvesting": { isValid = true; break; }
                case "flag": { isValid = true; break; }
                case "floating_fortress_level": { isValid = true; break; }
                case "food_cook": { isValid = true; break; }
                case "food_supply": { isValid = true; break; }
                case "fortress_track": { isValid = true; break; }
                case "gacha_reward_rate": { isValid = true; break; }
                case "gengduoxinxi": { isValid = true; break; }
                case "gerenxinxi": { isValid = true; break; }
                case "goldminer_level": { isValid = true; break; }
                case "goldminer_main": { isValid = true; break; }
                case "goldminer_map": { isValid = true; break; }
                case "goods_compose": { isValid = true; break; }
                case "goods": { isValid = true; break; }
                case "growth_gift": { isValid = true; break; }
                case "guide_freedom": { isValid = true; break; }
                case "help_link": { isValid = true; break; }
                case "hero_action": { isValid = true; break; }
                case "hero_advancement": { isValid = true; break; }
                case "hero_ai_list": { isValid = true; break; }
                case "hero_ai_state": { isValid = true; break; }
                case "hero_char_tag": { isValid = true; break; }
                case "hero_chat": { isValid = true; break; }
                case "hero_item_kind": { isValid = true; break; }
                case "hero_monthcard": { isValid = true; break; }
                case "hero_quest": { isValid = true; break; }
                case "hero_raiders": { isValid = true; break; }
                case "hero_skill": { isValid = true; break; }
                case "hero_skin_config": { isValid = true; break; }
                case "hero_skin_list": { isValid = true; break; }
                case "hero_sound": { isValid = true; break; }
                case "hero_try": { isValid = true; break; }
                case "heroes_camp": { isValid = true; break; }
                case "heroes_levelup": { isValid = true; break; }
                case "heroes_quality": { isValid = true; break; }
                case "heroes": { isValid = true; break; }
                case "heroevent_schedule": { isValid = true; break; }
                case "heroillustrate_power": { isValid = true; break; }
                case "heros_guide": { isValid = true; break; }
                case "honor_reward": { isValid = true; break; }
                case "honor_statue": { isValid = true; break; }
                case "hunting_squad": { isValid = true; break; }
                case "ignorefiles": { isValid = true; break; }
                case "information_tips": { isValid = true; break; }
                case "intelligence_level": { isValid = true; break; }
                case "intelligence_movie_group": { isValid = true; break; }
                case "intelligence_movie": { isValid = true; break; }
                case "intelligence": { isValid = true; break; }
                case "interactive_button": { isValid = true; break; }
                case "interface_setting": { isValid = true; break; }
                case "investigation": { isValid = true; break; }
                case "JP_movie": { isValid = true; break; }
                case "lack_res_link": { isValid = true; break; }
                case "language": { isValid = true; break; }
                case "legion_flag": { isValid = true; break; }
                case "legion_honor_access": { isValid = true; break; }
                case "legion_honor": { isValid = true; break; }
                case "lf_activity_map": { isValid = true; break; }
                case "lf_play_map": { isValid = true; break; }
                case "lf_season": { isValid = true; break; }
                case "loading_tips": { isValid = true; break; }
                case "lucky_bingo_item": { isValid = true; break; }
                case "lucky_bingo_main": { isValid = true; break; }
                case "mail": { isValid = true; break; }
                case "maincity_level": { isValid = true; break; }
                case "maincity_upgrade_panel": { isValid = true; break; }
                case "max_res_link": { isValid = true; break; }
                case "medal": { isValid = true; break; }
                case "meme_group": { isValid = true; break; }
                case "meme": { isValid = true; break; }
                case "metal_trade": { isValid = true; break; }
                case "model_people": { isValid = true; break; }
                case "mountings": { isValid = true; break; }
                case "movie_function": { isValid = true; break; }
                case "movie_ja": { isValid = true; break; }
                case "movie_npc_hepler": { isValid = true; break; }
                case "movie": { isValid = true; break; }
                case "name_limit": { isValid = true; break; }
                case "nationalflag": { isValid = true; break; }
                case "newbie_rank": { isValid = true; break; }
                case "noviceboot": { isValid = true; break; }
                case "pinball_path": { isValid = true; break; }
                case "play_cards": { isValid = true; break; }
                case "policy_affect": { isValid = true; break; }
                case "policy_amendment": { isValid = true; break; }
                case "policy_card": { isValid = true; break; }
                case "policy_point": { isValid = true; break; }
                case "policy_slot": { isValid = true; break; }
                case "postcard": { isValid = true; break; }
                case "posterShop": { isValid = true; break; }
                case "push_role": { isValid = true; break; }
                case "push_show": { isValid = true; break; }
                case "pve_fake_chapter": { isValid = true; break; }
                case "pve_fake_hero": { isValid = true; break; }
                case "pve_fake_route": { isValid = true; break; }
                case "pve_in_anniversary": { isValid = true; break; }
                case "pve_in_ipsubway": { isValid = true; break; }
                case "pve_in_main": { isValid = true; break; }
                case "pve_in_subway": { isValid = true; break; }
                case "pve_scene": { isValid = true; break; }
                case "pve_temp": { isValid = true; break; }
                case "pve": { isValid = true; break; }
                case "quest": { isValid = true; break; }
                case "question_language": { isValid = true; break; }
                case "questions": { isValid = true; break; }
                case "rank": { isValid = true; break; }
                case "rebel_siege_cityscore": { isValid = true; break; }
                case "rebel_siege_reward": { isValid = true; break; }
                case "rebel_siege": { isValid = true; break; }
                case "rec_science": { isValid = true; break; }
                case "recharge": { isValid = true; break; }
                case "reclaim_buliding": { isValid = true; break; }
                case "reclaim_chests": { isValid = true; break; }
                case "reclaim_decorate": { isValid = true; break; }
                case "reclaim_interact": { isValid = true; break; }
                case "reclaim_pve": { isValid = true; break; }
                case "reclaim_soil": { isValid = true; break; }
                case "reclaim": { isValid = true; break; }
                case "region_force_fund": { isValid = true; break; }
                case "region_force": { isValid = true; break; }
                case "regression_bp": { isValid = true; break; }
                case "regression_progress": { isValid = true; break; }
                case "remains_building": { isValid = true; break; }
                case "remains": { isValid = true; break; }
                case "res_shop": { isValid = true; break; }
                case "res_type": { isValid = true; break; }
                case "rescue_point": { isValid = true; break; }
                case "resource_point": { isValid = true; break; }
                case "reward_rate_tips": { isValid = true; break; }
                case "reward": { isValid = true; break; }
                case "ruins_exploration": { isValid = true; break; }
                case "S1_land": { isValid = true; break; }
                case "science": { isValid = true; break; }
                case "sciencegroup": { isValid = true; break; }
                case "scienceGroupName": { isValid = true; break; }
                case "score_quest": { isValid = true; break; }
                case "score": { isValid = true; break; }
                case "scrolling_announcement": { isValid = true; break; }
                case "season_book": { isValid = true; break; }
                case "season_bp_level": { isValid = true; break; }
                case "season_bp_quest": { isValid = true; break; }
                case "season_bp": { isValid = true; break; }
                case "season_building": { isValid = true; break; }
                case "season_function": { isValid = true; break; }
                case "season_phase": { isValid = true; break; }
                case "season_plot": { isValid = true; break; }
                case "season_rule": { isValid = true; break; }
                case "season_stage": { isValid = true; break; }
                case "season_warmup": { isValid = true; break; }
                case "series_quest": { isValid = true; break; }
                case "server_forces_buff": { isValid = true; break; }
                case "server_forces_reward": { isValid = true; break; }
                case "server_forces": { isValid = true; break; }
                case "server_season_exchange": { isValid = true; break; }
                case "server_season_honor_lv": { isValid = true; break; }
                case "skill_buff": { isValid = true; break; }
                case "skill": { isValid = true; break; }
                case "snowman_stage": { isValid = true; break; }
                case "sound": { isValid = true; break; }
                case "special_slot": { isValid = true; break; }
                case "staff": { isValid = true; break; }
                case "staffgift": { isValid = true; break; }
                case "stage_rate_detail": { isValid = true; break; }
                case "stage_rate_reward": { isValid = true; break; }
                case "stage": { isValid = true; break; }
                case "status": { isValid = true; break; }
                case "street_pve": { isValid = true; break; }
                case "suspect_filter": { isValid = true; break; }
                case "tactical_building": { isValid = true; break; }
                case "Tile_pattern": { isValid = true; break; }
                case "TileCrush": { isValid = true; break; }
                case "timeFly_clientEvent": { isValid = true; break; }
                case "timeFly_serverEvent": { isValid = true; break; }
                case "timeFly": { isValid = true; break; }
                case "timeFly_timeFly": { isValid = true; break; }
                case "touxiang": { isValid = true; break; }
                case "trade_go": { isValid = true; break; }
                case "trade_level": { isValid = true; break; }
                case "trade_long": { isValid = true; break; }
                case "trade": { isValid = true; break; }
                case "trends_function": { isValid = true; break; }
                case "trends": { isValid = true; break; }
                case "truck": { isValid = true; break; }
                case "underground_soil": { isValid = true; break; }
                case "vehicle_refitting": { isValid = true; break; }
                case "vehicle_sale": { isValid = true; break; }
                case "vip_random_shop": { isValid = true; break; }
                case "vip_shop": { isValid = true; break; }
                case "vip": { isValid = true; break; }
                case "vitality": { isValid = true; break; }
                case "vitalitylevel": { isValid = true; break; }
                case "water_area": { isValid = true; break; }
                case "wheel": { isValid = true; break; }
                case "worldcity_besiege": { isValid = true; break; }
                case "worldcity_color": { isValid = true; break; }
                case "worldcity_laboratory": { isValid = true; break; }
                case "worldcity_repair": { isValid = true; break; }
                case "worldcity_tower": { isValid = true; break; }
                case "worldcity_upgrade": { isValid = true; break; }
                case "worldcity": { isValid = true; break; }
                case "zenith_level": { isValid = true; break; }
                case "zenith_prestige": { isValid = true; break; }
                case "zenith_server": { isValid = true; break; }
                case "zenith_story": { isValid = true; break; }
                case "zombie_corps_soldier": { isValid = true; break; }
                case "zombie_guard": { isValid = true; break; }
                case "zombie_siege_reward": { isValid = true; break; }
                case "zombie_siege": { isValid = true; break; }
                case "zombiewar_mode": { isValid = true; break; }
                case "zombiewar_prop": { isValid = true; break; }
                case "zombiewar_set": { isValid = true; break; }

                default:{ isValid = ConfigManager.Instance.IsValidTable(tableName); break; }
            }

            return isValid;
        }
        
        #endregion Framework Method
    }
}